// Package kdf implements the key hierarchy of docs/FORMAT.md §3 and the
// byte-exact rules of §3.3: every derivation between a credential and the VMK,
// the subordinate keys below the VMK and the archive key, and the AES-256-GCM
// wrapping of the VMK and of 32-byte keys — including the 32-byte plaintexts
// of the secrets section (§7.6), whose padding rule for a 16-byte recovery key
// lives here beside the key itself.
//
// Every function here is pinned by testdata/kdf-vectors.json, which was
// generated by tools/kdfvec and confirmed against an independent clean-room
// implementation; vectors_test.go checks each intermediate value, so a
// transposed argument or a wrong info string fails a test instead of producing
// 32 plausible bytes.
//
// Secrets pass through this package as ordinary byte slices and arrays.
// Callers that keep a secret for longer than one derivation — the VMK, the
// vault's K_P and the session's KWK — move it into an internal/secmem buffer,
// which is off the Go heap and locked out of the pagefile; this package zeroes
// its own intermediates where Go allows it and makes no stronger promise
// (DESIGN.md §14). A derivation here copies what it is handed whatever the
// caller keeps it in — HKDF copies the IKM, Argon2 fills megabytes, the AEAD
// builds an AES key schedule — and those copies are the ones SCOPE.md's line
// leaves outside the wrapper. Key objects from crypto/ecdh and crypto/mlkem
// hold their private material in fields this package cannot reach and offer no
// wipe, so they are outside that discipline.
package kdf
