// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveDetails is one registry record read whole (APP.md §13): hex strings
 * for ids and hashes, Unix seconds for times, the policy as named booleans.
 * It carries no wrapped_archive_key, no nonce and no offset, so §1's boundary
 * holds.
 */
export interface ArchiveDetails {
    "archiveId": string;
    "name": string;
    "description": string;
    "createdAt": number;
    "lastPath": string;
    "currentKid": string;
    "revision": number;
    "lastWriter": string;
    "lastSeq": number;
    "hashAtSeq": number;
    "lastCiphertextHash": string;
    "lastStoredSize": number;
    "lastWrittenAt": number;
    "forgottenAt": number;
    "alwaysRequireFullAuth": boolean;
    "hidden": boolean;

    /**
     * Method is the compression the archive was created with — store |
     * fastest | normal | better | best (FORMAT.md §7.1 bits 2–5).
     */
    "method": string;
    "versions": VersionView[] | null;
}

/**
 * ArchiveStat is the open archive's status strip. There is no Dirty, no
 * CapAt and no SessionAlive since 2026-09-09 — every operation is its own
 * transaction, so the archive is clean between them — and no ExpiresAt since
 * 2026-09-10: an open archive has no timeout of its own, so there is no
 * deadline to show (APP.md §2.3, DESIGN.md §10).
 */
export interface ArchiveStat {
    "seq": number;
    "id": string;
    "name": string;
    "size": number;
    "files": number;

    /**
     * Records counts live files and directories together, which is what
     * Extract all is greyed on: the file count alone cannot say whether the
     * tree holds anything (APP.md §3).
     */
    "records": number;
    "freeSpace": number;
    "keyVersion": number;
    "lastSavedAt": number;
    "state": string;
    "receiptOwed": boolean;

    /**
     * the file is not the copy the vault last saw
     */
    "copyMismatch": boolean;
}

/**
 * ArchiveSummary is a row of the archives list, from the registry plus
 * what the core knows about open archives.
 */
export interface ArchiveSummary {
    "id": string;
    "name": string;
    "path": string;
    "storedSize": number;
    "lastWrittenAt": number;
    "keyVersion": number;
    "open": boolean;
    "receiptOwed": boolean;

    /**
     * Method is how the archive is compressed — store | fastest | normal |
     * better | best — read from the record's policy (FORMAT.md §7.1 bits
     * 2–5) and followed by every writer of it.
     */
    "method": string;
    "hidden": boolean;

    /**
     * commits since the hash was refreshed
     */
    "hashBehind": number;
    "note"?: Code;

    /**
     * Description is the record's own second line and ForgottenAt is zero
     * unless the record was forgotten, in which case it is the modified_at
     * of the write that forgot it (FORMAT.md §7.1, §18.2; APP.md §13).
     */
    "description"?: string;
    "forgottenAt": number;

    /**
     * For open archives only.
     */
    "files": number;
    "freeSpace": number;

    /**
     * open | compacting | needs_reopen
     */
    "state"?: string;
}

/**
 * CeremonyState is the ceremony as the panel shows it.
 */
export interface CeremonyState {
    "seq": number;

    /**
     * unlock | create | enroll | remove | rotate | export | import | setup | verify | reveal | entangle
     */
    "kind": string;

    /**
     * Method is the way in this ceremony took: token | password | recovery.
     * The lock screen's wording follows the way in chosen, not whether a
     * secret was asked — with the vault's password on, a token unlock asks
     * for one too (APP.md §2.2, §13).
     */
    "method"?: string;
    "step": CeremonyStep;
    "promptId"?: string;

    /**
     * the prompt asks for a new secret (create, enrol), not an existing one
     */
    "choose": boolean;
    "slotLabel"?: string;

    /**
     * RecoveryID is the recovery key's ID at StepRecovery, XXXX-XXXX
     * (FORMAT.md §18.4): the sheet the digits belong to.
     */
    "recoveryId"?: string;
    "retries": number;
    "retriesKnown": boolean;
    "verified": boolean;
    "readerCount": number;

    /**
     * touch ordinal on this token handle
     */
    "n": number;
    "pinAsked": boolean;
    "error"?: Code;

    /**
     * SwapKey: the labels involved.
     */
    "removeLabel"?: string;
    "insertLabel"?: string;

    /**
     * Verify, at Done: how many archives the backup's registry names.
     */
    "archives": number;
}

/**
 * CeremonyStep is where the unlock or enrollment ceremony is.
 */
export enum CeremonyStep {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StepWaitingForKey = "waiting_for_key",
    StepTwoKeys = "two_keys",
    StepProbing = "probing",
    StepNoMatch = "no_match",
    StepBusy = "busy",
    StepPassword = "password",
    StepPIN = "pin",
    StepTouch = "touch",
    StepBlocked = "blocked",
    StepDeriving = "deriving",
    StepManagementKey = "management_key",
    StepRecovery = "recovery",
    StepRecords = "records",
    StepSwapKey = "swap_key",
    StepReleasing = "releasing",
    StepDone = "done",
    StepFailed = "failed",
};

/**
 * ChildRef is one child of a directory as Children answers it (APP.md §3):
 * the record's id and its kind, nothing else — enough for the header's
 * tick and Ctrl+A to select the folder, and for a Delete's question to
 * count files and folders apart when the selection reaches past the rows
 * loaded, without a row rendered for each.
 */
export interface ChildRef {
    "id": string;
    "isDir": boolean;
}

/**
 * Code is what the frontend sees of an error: a stable identifier it maps
 * to copy, and nothing else. The original error — with its offsets,
 * generations and file names — goes to the core's log only (APP.md §3).
 */
export enum Code {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CodeInternal = "internal",

    /**
     * Vault and session.
     */
    CodeNoVault = "vault.none",
    CodeVaultLocked = "vault.locked",
    CodeVaultBroken = "vault.broken",
    CodeVaultBusy = "vault.busy",
    CodeVaultTampered = "vault.tampered",

    /**
     * The two causes, for VaultStatus.TamperedReason and the park a
     * mismatch leaves: the slot region does not match the registry (R25),
     * or it does not belong with the superblock (FORMAT.md §6.2).
     */
    CodeTamperedHash = "vault.tampered_hash",
    CodeTamperedGeneration = "vault.tampered_generation",
    CodeVaultStale = "vault.stale",
    CodeVaultNotFound = "vault.not_found",
    CodeVaultInvalid = "vault.invalid",

    /**
     * a vault is already kept; importing needs replace
     */
    CodeVaultExists = "vault.exists",

    /**
     * the vault has only a recovery slot: finish setup
     */
    CodeSetupNeeded = "vault.setup_needed",

    /**
     * close the open archives before replacing the vault
     */
    CodeArchivesOpen = "vault.archives_open",

    /**
     * lock the vault first
     */
    CodeVaultUnlocked = "vault.unlocked",

    /**
     * warning: the vault's place could not be recorded
     */
    CodeSettingsUnsaved = "settings.unsaved",
    CodeNeedsUnlock = "vault.needs_unlock",
    CodeAuth = "vault.auth",
    CodeNoSlot = "vault.no_slot",
    CodePasswordNeeded = "vault.password_required",

    /**
     * a chosen password under the minimum
     */
    CodePasswordShort = "vault.password_short",
    CodeInvariant = "vault.invariant",
    CodeSlotPolicy = "vault.slot_policy",
    CodeDuplicateSlot = "vault.duplicate_slot",
    CodeNoRecoverySlot = "vault.no_recovery_slot",
    CodeSlotNotFound = "vault.slot_not_found",

    /**
     * the vault keeps no copy of this recovery key: add a new one, then remove this
     */
    CodeEscrowMissing = "vault.escrow_missing",

    /**
     * the kept recovery key does not open its slot: never shown
     */
    CodeEscrowMismatch = "vault.escrow_mismatch",

    /**
     * a recovery key is not saved into the data folder, the vault's folder or under a staging name
     */
    CodeRecoveryPlace = "vault.recovery_place",

    /**
     * a vault is kept: a second one is never made; only a damaged one is rebuilt
     */
    CodeVaultKept = "vault.kept",

    /**
     * CodeNotThisVault: no VMK of this vault and no key given opened the
     * incoming registry — another vault, or a backup from a generation this
     * vault no longer keeps. Never corruption (FORMAT.md §18.2, APP.md §13).
     */
    CodeNotThisVault = "vault.not_this_vault",
    CodeConflict = "vault.conflict",
    CodeIndeterminate = "vault.indeterminate",
    CodeCeremonyRunning = "ceremony.in_progress",
    CodeReleasing = "ceremony.releasing",
    CodeNoCeremony = "ceremony.none",
    CodeStalePrompt = "ceremony.stale_prompt",
    CodeCancelled = "ceremony.cancelled",

    /**
     * Token.
     */
    CodeTokenNoService = "token.no_service",
    CodeTokenNoReader = "token.no_reader",
    CodeTokenNoCard = "token.no_card",
    CodeTokenBusy = "token.busy",
    CodeTokenNoPIV = "token.no_piv",
    CodeTokenUnsupport = "token.unsupported",
    CodeTokenNoKey = "token.no_key",
    CodeTokenNotUsable = "token.not_usable",
    CodeTokenPIN = "token.pin",

    /**
     * the key's agreement does not match its public key: not enrolled
     */
    CodeTokenProof = "token.proof",
    CodeTokenPINBlocked = "token.pin_blocked",
    CodeTokenPINAgain = "token.pin_required",
    CodeTokenTouch = "token.touch",

    /**
     * a cancelled ceremony's key call is still answering: the file or the card is held until it does
     */
    CodeTokenPending = "token.pending",

    /**
     * CodePasswordDeadline: the five minutes from the touch ran out with
     * the vault's password not given, so the kept shared secret went and
     * the ceremony ended at the lock screen's first step (APP.md §2.2).
     * "The password was not given within five minutes; unlock again from
     * the key."
     */
    CodePasswordDeadline = "token.password_deadline",
    CodeTokenTooMany = "token.too_many_operations",
    CodeTokenReset = "token.reset_failed",
    CodeTokenOccupied = "token.slot_occupied",
    CodeTokenFull = "token.no_empty_slot",
    CodeTokenNoMgmtKey = "token.no_protected_management_key",
    CodeTokenMgmtKey = "token.management_key",
    CodeTokenTwoKeys = "token.two_keys",

    /**
     * Archives.
     */
    CodeArchiveNotOpen = "archive.not_open",
    CodeArchiveOpen = "archive.already_open",

    /**
     * archive.dirty is archive.ErrTxOpen alone since 2026-09-09: two
     * transactions on one handle, a bug and not a state (APP.md §2.3 — an
     * archive is clean between operations, so no user can be in this one).
     */
    CodeArchiveDirty = "archive.dirty",
    CodeArchiveBusy = "archive.busy",
    CodeArchiveCompacting = "archive.compacting",
    CodeArchiveNeedsReopen = "archive.needs_reopen",
    CodeArchiveKey = "archive.key",
    CodeArchiveReadOnly = "archive.read_only",
    CodeArchiveNotFound = "archive.not_found",
    CodeArchiveInvalid = "archive.invalid",
    CodeArchiveMissing = "archive.file_missing",
    CodeArchiveCopyMismatch = "archive.copy_mismatch",

    /**
     * Forget, restore and delete (APP.md §13). A forgotten record still
     * holds its keys, so every other operation on it says so rather than
     * archive.not_found, which stays the answer for a record already purged.
     */
    CodeArchiveForgotten = "archive.forgotten",

    /**
     * CodeArchiveNotThisOne: the parent folder was opened and the leaf was
     * not in it, or the envelope holds another archive_id. Nothing removed;
     * the page asks once more before forgetting.
     */
    CodeArchiveNotThisOne = "archive.not_this_archive",

    /**
     * CodeArchiveUnreachable: the volume, share or folder is not there.
     * Nothing removed and nothing forgotten.
     */
    CodeArchiveUnreachable = "archive.file_unreachable",

    /**
     * CodeArchiveDeleteFailed: the archive_id matched and the removal still
     * failed. The record is kept, since its keys open a file that is there.
     */
    CodeArchiveDeleteFailed = "archive.delete_failed",

    /**
     * CodeDescriptionLong: over MaxDescriptionLen bytes, or not UTF-8
     * (FORMAT.md §7.1).
     */
    CodeDescriptionLong = "archive.description_long",

    /**
     * CodeArchiveName: an empty name, one over 1 024 bytes or one that is
     * not UTF-8. Bounded app-side only: the confirmation for Forget and
     * Delete is the archive's name typed (APP.md §13, FORMAT.md §7.4).
     */
    CodeArchiveName = "archive.name_invalid",

    /**
     * CodeArchiveExists: the path a create was given already holds a file.
     * The archive layer creates with O_EXCL and Enfold never overwrites a
     * file it did not make (APP.md §6, DESIGN.md trap 28). "A file is
     * already there. Enfold never overwrites; choose another name."
     */
    CodeArchiveExists = "archive.exists",
    CodeFileExists = "file.exists",
    CodeFileNotFound = "file.not_found",
    CodeFileName = "file.name",

    /**
     * The three per-item codes of the tree (APP.md §3, FORMAT.md R39).
     * CodeKindMismatch: the incoming item and the item in the way are of
     * different kinds, and kinds that differ never replace — replacing a
     * folder with a file would tombstone its subtree in one write, and
     * replacing a file with a folder is not an edit of that file.
     */
    CodeKindMismatch = "file.kind_mismatch",

    /**
     * CodeMoveIntoSelf: a directory would be moved into itself or into one
     * of its own descendants.
     */
    CodeMoveIntoSelf = "file.move_into_self",

    /**
     * CodeTreeBounds: the change would stand a directory more than 255
     * parents from the root, or join a record to a path over 4096 bytes.
     * Both bounds are the moved or created subtree's and not the named
     * record's, so they are caught in the pre-flight rather than at the
     * seal.
     */
    CodeTreeBounds = "file.tree_bounds",
    CodeSourceChanged = "file.source_changed",

    /**
     * The two refusals of an extract's destination (APP.md §3, ruled
     * 2026-09-10). R20 holds Windows' rules on the way in, so the name
     * itself fits a Windows volume; what cannot be known beforehand is the
     * path's whole length and the volume's own limit (an SMB share, an
     * exFAT stick), and only the destination's refusal says so.
     * CodeFileNameRefused: the final name — a file's on placement, or a
     * directory's on its creation, whose subtree is then reported once for
     * its top — was refused: the outcome `name_refused`, and the page
     * offers Shorten, Rename… and Skip. "The destination cannot take a name
     * this long."
     */
    CodeFileNameRefused = "file.name_refused",

    /**
     * CodeFilePathRefused: the temporary — a fixed short name in the same
     * folder — was refused, so the path and not the leaf is the problem
     * and no name helps — the outcome `path_refused`, Skip and Skip all
     * like it. "The folder's path is too long for this destination." The
     * destination root's own refusal is the operation's error under this
     * code, before any outcome.
     */
    CodeFilePathRefused = "file.path_refused",
    CodeContentHash = "file.content_hash",
    CodeNoSpace = "archive.no_space",
    CodeDictInUse = "archive.dictionary_in_use",
    CodeOpNotFound = "op.not_found",
    CodeOpCancelled = "op.cancelled",

    /**
     * CodeOpCommitting: the cancel arrived after the writing was done and
     * the commit had been entered, which runs under a context no cancel
     * reaches. The change is being published and the operation's result will
     * say so, so the cancel is refused rather than answered as if it had
     * worked (the outside audit of 2026-09-09). "The operation is already
     * being saved; it will finish."
     */
    CodeOpCommitting = "op.committing",
    CodeOpRunning = "op.in_progress",
    CodeTooSlow = "op.too_slow_for_session",

    /**
     * CodeReclaimIncomplete: a move commit of the reclaim the core runs
     * after an edit failed. The edit itself committed and stays committed;
     * the reclaim's own operation ends with this, and the next qualifying
     * commit takes the run up again (APP.md §2.3). "Saved. Reclaiming space
     * did not finish."
     */
    CodeReclaimIncomplete = "archive.reclaim_incomplete",

    /**
     * The drag out of the window (APP.md §3, dragout.go). CodeDragUnsupported:
     * OLE could not be initialised on the window's thread, or this is not
     * Windows, so no native drag can run; CodeDragBusy: a drag is already
     * running, and two cannot run at once in one process.
     */
    CodeDragUnsupported = "drag.unsupported",
    CodeDragBusy = "drag.busy",
    CodeParams = "params",
    CodeIO = "io",
};

/**
 * Collision is what CheckNames reports: the kind on both sides — what is
 * being offered and what is in the way — so the dialog can say "Photos is a
 * file here" and grey Replace whenever the two differ (APP.md §3).
 */
export interface Collision {
    /**
     * the name as it was offered
     */
    "name": string;

    /**
     * the kind offered: a name given with a trailing "/"
     */
    "isDir": boolean;
    "existing": string;
    "existingIsDir": boolean;
}

/**
 * Crumb is one step of the breadcrumb: a directory's id and its name, the
 * root's being the archive's own name (APP.md §3).
 */
export interface Crumb {
    "id": string;
    "name": string;
}

/**
 * Difference is one field an incoming record holds differently: the local
 * value is kept and the row says what the other vault had (APP.md §13).
 */
export interface Difference {
    /**
     * name | description | policy
     */
    "field": string;

    /**
     * rendered for display only
     */
    "theirs": string;
}

/**
 * DragOutResult is what Shell.DragOut answers once the native drag's
 * DoDragDrop has returned (APP.md §3): whether the release was a self-drop —
 * the page then performs a Move of the ids in flight — whether the
 * extraction had run by then, DoDragDrop's own effect (DROPEFFECT_NONE for
 * an asynchronous drop whatever the target did), the staging folder the
 * drop's paths lie under, and the id of the dragout operation the strip
 * follows.
 */
export interface DragOutResult {
    "selfDrop": boolean;
    "extracted": boolean;
    "effect": number;
    "folder": string;
    "opId": string;
}

/**
 * EntangledState is the Keys page's row for the vault's password (APP.md
 * §13): whether the switch is on, and whether it could be turned on at all.
 */
export interface EntangledState {
    "on": boolean;
    "canEnable": boolean;

    /**
     * vault.invariant when CanEnable is false
     */
    "reason"?: Code;
}

/**
 * ExistingFile is the file already in the destination, as a stat taken after
 * the collision was seen — by the cheap pre-check or by the exclusive
 * create's refusal — says it. The stat decides nothing: nothing is ever
 * placed over a file on a stat's word (APP.md §3).
 */
export interface ExistingFile {
    "size": number;
    "modifiedAt": number;
}

/**
 * FileInfo is what a backup file says about itself before any unlock.
 */
export interface FileInfo {
    "path": string;

    /**
     * vault | backup (recovery slots only, R28)
     */
    "kind": string;
    "modifiedAt": number;

    /**
     * the same vault as the one kept (plaintext; proven only by an unlock)
     */
    "vaultMatches": boolean;
    "slotCount": number;

    /**
     * slots by kind, so a confirmation can say what is traded away
     */
    "hardware": number;
    "password": number;
    "recovery": number;

    /**
     * than the vault kept (plaintext, R35: dated, not authenticated)
     */
    "newer": boolean;

    /**
     * RecoverySlots names the file's recovery slots and Generation is its
     * plaintext vmk_generation (FORMAT.md §5): both inform a dialog and
     * decide nothing (APP.md §13, FORMAT.md §18.2).
     */
    "recoverySlots": SlotBrief[] | null;
    "generation": number;
}

/**
 * FileOutcome is one record's result inside a batch operation. IsDir tells a
 * directory's outcome from a file's: created (a directory record made) and
 * entered (an existing one descended into) are a directory's, added and
 * replaced a file's (APP.md §3). name_refused and path_refused are an
 * extract's (ruled 2026-09-10): the destination would not take the final
 * name — a file's or a directory's, whose subtree is then reported once,
 * for its top — or the temporary's path, and the rest of the batch was
 * written; Path is then the name that was refused.
 * 
 * ID, Size and ModifiedAt are the archive copy's — the record's id as every
 * other view spells it (32 lowercase hex digits), its plaintext size and its
 * modified_at — set on every extract outcome, where the record is known
 * before the first byte, and on an add's or a replace's where they are known
 * as the item is written; zero where they are not. They are what lets the
 * page re-issue an extract for the conflicts it was told about, and draw the
 * compare list's archive side, without walking the tree (APP.md §3).
 */
export interface FileOutcome {
    /**
     * Path is the file on disk — an add's source, an extract's destination,
     * the path actually written when a `names` entry renamed the record
     * for that extract — and Name the record's joined archive path.
     */
    "path": string;
    "name": string;
    "isDir": boolean;

    /**
     * added | replaced | created | entered | skipped | extracted | conflict | name_refused | path_refused | failed
     */
    "outcome": string;
    "code"?: Code;

    /**
     * ID is the record's id, empty where the outcome has none yet (a source
     * an add refused or skipped, a folder it could not make).
     */
    "id"?: string;

    /**
     * the archive copy's plaintext size; 0 for a directory
     */
    "size": number;

    /**
     * the archive copy's modified_at
     */
    "modifiedAt": number;

    /**
     * Existing is the file that was in the way, on the conflict outcome of an
     * extract with the ask policy and on nothing else (APP.md §3, ruled
     * 2026-09-10): what the page shows in its Replace / Skip / Compare
     * dialogs before it re-issues the extract for the ids the user chose.
     */
    "existing"?: ExistingFile | null;
}

/**
 * FileRow is one row of a page: one committed record, file or directory
 * alike (APP.md §3). ID and ParentID are the record's own ids — 32 lowercase
 * hex digits, the all-zero id being the root — Name is the record's own name
 * and Path the joined one (FORMAT.md R20, R39). A directory's Size is the
 * sum beneath it and its ModifiedAt the record's own. A row is committed or
 * it is not listed: there is no pending word since 2026-09-09.
 */
export interface FileRow {
    "id": string;
    "parentId": string;
    "isDir": boolean;
    "name": string;
    "path": string;
    "size": number;

    /**
     * raw | zstd | zstd+dict
     */
    "storage": string;
    "savedPercent": number;
    "modifiedAt": number;
}

/**
 * IncomingRecord is one row of a merge's checklist (APP.md §13). Action is
 * what ticking it would do; Ticked is the default.
 */
export interface IncomingRecord {
    "archiveId": string;
    "name": string;
    "description": string;
    "createdAt": number;

    /**
     * key versions the incoming record holds
     */
    "versions": number;

    /**
     * skip | version | add | forgotten
     */
    "action": string;
    "forgottenAt": number;
    "differs": Difference[] | null;
    "ticked": boolean;
}

/**
 * OpView is a running or finished long operation. Kind is add | replace |
 * extract | compact | reclaim | verify | rotate | dragout; reclaim is the in-place
 * compaction the core runs itself after a commit, or after the last reader
 * closes, when the plan would give the file system enough of the tail back
 * (APP.md §2.3, FORMAT.md R40), and the strip shows it as Reclaiming space.
 */
export interface OpView {
    "id": string;
    "kind": string;
    "archiveId"?: string;
    "done": number;
    "total": number;

    /**
     * Items is what the operation plans: the files an add, a replace or an
     * extract will write, known once the plan is made and zero before that
     * and for every operation without a count. It is what lets the strip say
     * "Adding 3 files" rather than a phase word — and "Adding 1 file", since
     * a count of one is singular wherever the page counts (APP.md §3).
     */
    "items": number;

    /**
     * DragItems is what a drag out carries: the records the gesture names,
     * files and folders alike, which is what the strip counts for it —
     * "Extracting 3 items" through all three of its phases (APP.md §3,
     * ruled 2026-09-11 after the first real drag). It is not Items: a
     * folder dragged out is one item and however many files the extraction
     * writes beneath it, and the strip's bar is still those files' bytes.
     * Zero for every other kind.
     */
    "dragItems": number;
    "phase": string;
    "startedAt": number;
    "finished": boolean;
    "error"?: Code;
    "results"?: FileOutcome[] | null;

    /**
     * Policy and Destination are an extract's — replace | skip | rename | ask,
     * and the folder it writes under — and empty for every other kind, so
     * that the conflict question is derived from the operation itself in the
     * store: it survives the page's remount across the lock scene and cannot
     * be lost to a race between the call's return and the operation's end
     * (APP.md §3).
     */
    "policy"?: string;
    "destination"?: string;

    /**
     * Returned is what a reclaim gave the file system back once it ended:
     * the file's size before the run less its size after, which is what the
     * page says — "Reclaimed 1.2 GB" — and is never the bytes it moved
     * (APP.md §2.3). Zero for every other kind, and for a run that ended
     * before its first commit.
     */
    "returned": number;

    /**
     * DragResult is how a drag out ended, on a finished dragout and nothing
     * else (APP.md §3, dragout.go). The drop is synchronous — the data
     * object offers no IDataObjectAsyncCapability, so the target must finish
     * inside Drop — and DoDragDrop's return says which of six it was:
     * self_drop, the button came up over Enfold's own window, nothing was
     * extracted and the page performs the Move of the ids it kept in flight;
     * moved, the effect was move and the staged items are gone; copied, the
     * effect was copy; cancelled, no effect at all — Escape, a release over
     * nothing, Explorer's Skip or its dialog cancelled, all of them a drop
     * that is over; refused, the target never asked for the paths; failed,
     * the extraction or the drag itself. A dragout's Phase is dragging
     * during the hover, preparing while the drop's request runs the
     * extraction — Items and Total say what it writes — and awaiting, with
     * Done at Total, from the extraction's end until DoDragDrop returns.
     */
    "dragResult"?: string;
}

/**
 * Page is one screenful of one directory. Total counts that directory's
 * children, not its subtree, and Crumbs is the chain from the root down to
 * the folder shown, inclusive and never empty — the page draws the whole
 * breadcrumb from it and takes no name from Stat.
 */
export interface Page {
    "seq": number;
    "rows": FileRow[] | null;
    "total": number;
    "crumbs": Crumb[] | null;
}

/**
 * Reader is a PC/SC reader that looks like a YubiKey.
 */
export interface Reader {
    "name": string;
}

/**
 * Settings is the machine-local settings file plus the registry's timeouts.
 */
export interface Settings {
    "vaultPath": string;
    "displayName": string;

    /**
     * destroy | hide
     */
    "closeToTray": string;

    /**
     * system | light | dark
     */
    "theme": string;

    /**
     * native
     */
    "look": string;
    "recoveryRecordPct": number;
    "dictionaryBelow": number;

    /**
     * LastArchiveFolder is where the last archive was created, for the New
     * archive dialog (APP.md §6): read-only, since only a create writes it.
     * An extract's destination is not remembered — the page prefills it from
     * the archive's own folder (§3, ruled 2026-09-10).
     */
    "lastArchiveFolder": string;

    /**
     * from the registry; 0 = default
     */
    "idleMinutes": number;

    /**
     * from the registry; 0 = default
     */
    "absoluteMinutes": number;
    "timeoutsFromVault": boolean;

    /**
     * only while unlocked
     */
    "timeoutsAdjustable": boolean;
}

/**
 * SlotBrief names one recovery slot of an incoming file, so that a dialog
 * can say which key it will want before the button is pressed (APP.md §13).
 */
export interface SlotBrief {
    "recipientId": string;
    "label": string;
    "createdAt": number;
}

/**
 * SlotView describes a way to unlock. Whether a hardware slot needs the
 * vault's password is not a slot fact since Revision 2 — it is
 * VaultStatus.Entangled — and every recovery slot has its kept key from the
 * commit that made it (FORMAT R38), so neither is on the view.
 */
export interface SlotView {
    "recipientId": string;

    /**
     * hardware | password | recovery
     */
    "type": string;
    "label": string;
    "createdAt": number;

    /**
     * RecoveryID is the key's ID, XXXX-XXXX, on recovery slots only
     * (FORMAT.md §18.4): it catches the wrong sheet before a digit is typed.
     */
    "recoveryId"?: string;

    /**
     * the invariant would still hold without it (keystore.Removable)
     */
    "removable": boolean;
}

/**
 * TextPreview is a text file's head for the preview pane.
 */
export interface TextPreview {
    "text": string;
    "truncated": boolean;
}

/**
 * VaultState is the session's state.
 */
export enum VaultState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * no vault configured yet
     */
    StateNone = "none",

    /**
     * keys not in memory
     */
    StateLocked = "locked",

    /**
     * a ceremony is running
     */
    StateUnlocking = "unlocking",

    /**
     * a ceremony is ending; the card is being released
     */
    StateReleasing = "releasing",
    StateUnlocked = "unlocked",

    /**
     * a commit's outcome is unknown; Reopen
     */
    StateBroken = "broken",

    /**
     * the vault file is open in another process
     */
    StateBusy = "busy",
};

/**
 * VaultStatus is the whole state the frontend renders from; every field is
 * safe to show.
 */
export interface VaultStatus {
    "seq": number;
    "state": VaultState;
    "path": string;
    "displayName": string;
    "lastUnlockedAt": number;

    /**
     * idle deadline, 0 when locked
     */
    "locksAt": number;

    /**
     * absolute deadline, 0 when locked
     */
    "absoluteAt": number;

    /**
     * the keystore's own date (R35)
     */
    "modifiedAt": number;

    /**
     * Entangled is the slot region header's switch (FORMAT.md §6, §18.1):
     * the vault's password, not a slot's, and a plaintext fact the lock
     * screen has while Locked.
     */
    "entangled": boolean;

    /**
     * VaultFileSize is the vault file's own size, for the Archives header
     * line (APP.md §13).
     */
    "vaultFileSize": number;
    "tampered": boolean;

    /**
     * TamperedReason names which check said so: vault.tampered_hash (the
     * slot region does not match the registry, R25) or
     * vault.tampered_generation (the slot region and the superblock do not
     * belong together, FORMAT.md §6.2).
     */
    "tamperedReason"?: Code;
    "warnings": Code[] | null;
    "ceremony"?: CeremonyState | null;
    "ops": OpView[] | null;
    "openArchives": number;
    "hasPasswordSlot": boolean;
    "hasHardwareSlot": boolean;

    /**
     * PendingTouch: a cancelled ceremony's key call is still answering —
     * the key waits for a touch — and an unlock can pick it up (§2.2).
     */
    "pendingTouch": boolean;

    /**
     * Note is the quiet line the lock screen carries from a ceremony that
     * has already ended: token.password_deadline, the five minutes from
     * the touch running out with the vault's password not given (§2.2).
     * The next ceremony clears it.
     */
    "note"?: Code;

    /**
     * only a recovery slot: FinishSetup is the one action
     */
    "setupNeeded": boolean;

    /**
     * where the vault lives unless kept elsewhere
     */
    "defaultPath": string;

    /**
     * a configured vault that could not be opened at start
     */
    "missingPath": string;

    /**
     * the vault is not at DefaultPath (the override is set)
     */
    "keptElsewhere": boolean;

    /**
     * vault-replaced-*.eks files in the data folder
     */
    "retiredCopies": number;

    /**
     * the newest of them
     */
    "retiredPath": string;

    /**
     * MissingPath is there and not a keystore: the rebuild of APP.md §2.1 applies
     */
    "damaged": boolean;

    /**
     * the newest vault-damaged-*.eks kept for salvage
     */
    "damagedCopyPath": string;
}

/**
 * VersionView is one key version of an archive record (FORMAT.md §7.2), for
 * the details modal: a key, never a snapshot, and never the key itself.
 */
export interface VersionView {
    "kid": string;
    "createdAt": number;
    "retiredAt": number;

    /**
     * current | retired
     */
    "state": string;
}
