// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveStat is the open archive's status strip.
 */
export interface ArchiveStat {
    "seq": number;
    "id": string;
    "name": string;
    "size": number;
    "files": number;
    "freeSpace": number;
    "keyVersion": number;
    "lastSavedAt": number;
    "dirty": number;
    "state": string;

    /**
     * the archive's own idle deadline
     */
    "expiresAt": number;

    /**
     * the dirty cap, 0 when clean
     */
    "capAt": number;
    "receiptOwed": boolean;

    /**
     * Save is possible now
     */
    "sessionAlive": boolean;
}

/**
 * ArchiveSummary is a row of the archives list, from the registry plus
 * what the core knows about open archives.
 */
export interface ArchiveSummary {
    "id": string;
    "name": string;
    "path": string;
    "storedSize": number;
    "lastWrittenAt": number;
    "keyVersion": number;
    "open": boolean;
    "dirty": number;
    "receiptOwed": boolean;
    "noCompression": boolean;
    "hidden": boolean;

    /**
     * commits since the hash was refreshed
     */
    "hashBehind": number;
    "note"?: Code;

    /**
     * For open archives only.
     */
    "files": number;
    "freeSpace": number;

    /**
     * open | dirty | compacting | needs_reopen
     */
    "state"?: string;
}

/**
 * BackupInfo is what a backup file says about itself before any unlock.
 */
export interface BackupInfo {
    "path": string;
    "modifiedAt": number;
    "vaultMatches": boolean;
    "slotCount": number;

    /**
     * than this vault
     */
    "newer": boolean;
}

/**
 * CeremonyState is the ceremony as the panel shows it.
 */
export interface CeremonyState {
    "seq": number;

    /**
     * unlock | enroll | rewrap | restore
     */
    "kind": string;
    "step": CeremonyStep;
    "promptId"?: string;
    "slotLabel"?: string;
    "retries": number;
    "retriesKnown": boolean;
    "verified": boolean;
    "readerCount": number;

    /**
     * touch ordinal on this token handle
     */
    "n": number;
    "pinAsked": boolean;
    "error"?: Code;

    /**
     * SwapKey: the labels involved.
     */
    "removeLabel"?: string;
    "insertLabel"?: string;
}

/**
 * CeremonyStep is where the unlock or enrollment ceremony is.
 */
export enum CeremonyStep {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StepWaitingForKey = "waiting_for_key",
    StepTwoKeys = "two_keys",
    StepProbing = "probing",
    StepNoMatch = "no_match",
    StepBusy = "busy",
    StepPassword = "password",
    StepPIN = "pin",
    StepTouch = "touch",
    StepBlocked = "blocked",
    StepDeriving = "deriving",
    StepManagementKey = "management_key",
    StepRecovery = "recovery",
    StepSwapKey = "swap_key",
    StepReleasing = "releasing",
    StepDone = "done",
    StepFailed = "failed",
};

/**
 * Code is what the frontend sees of an error: a stable identifier it maps
 * to copy, and nothing else. The original error — with its offsets,
 * generations and file names — goes to the core's log only (APP.md §3).
 */
export enum Code {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CodeInternal = "internal",

    /**
     * Vault and session.
     */
    CodeNoVault = "vault.none",
    CodeVaultLocked = "vault.locked",
    CodeVaultBroken = "vault.broken",
    CodeVaultBusy = "vault.busy",
    CodeVaultTampered = "vault.tampered",
    CodeVaultStale = "vault.stale",
    CodeVaultNotFound = "vault.not_found",
    CodeVaultInvalid = "vault.invalid",
    CodeNeedsUnlock = "vault.needs_unlock",
    CodeAuth = "vault.auth",
    CodeNoSlot = "vault.no_slot",
    CodePasswordNeeded = "vault.password_required",
    CodeInvariant = "vault.invariant",
    CodeSlotPolicy = "vault.slot_policy",
    CodeDuplicateSlot = "vault.duplicate_slot",
    CodeNoRecoverySlot = "vault.no_recovery_slot",
    CodeSlotNotFound = "vault.slot_not_found",
    CodeConflict = "vault.conflict",
    CodeIndeterminate = "vault.indeterminate",
    CodeCeremonyRunning = "ceremony.in_progress",
    CodeReleasing = "ceremony.releasing",
    CodeNoCeremony = "ceremony.none",
    CodeStalePrompt = "ceremony.stale_prompt",
    CodeCancelled = "ceremony.cancelled",

    /**
     * Token.
     */
    CodeTokenNoService = "token.no_service",
    CodeTokenNoReader = "token.no_reader",
    CodeTokenNoCard = "token.no_card",
    CodeTokenBusy = "token.busy",
    CodeTokenNoPIV = "token.no_piv",
    CodeTokenUnsupport = "token.unsupported",
    CodeTokenNoKey = "token.no_key",
    CodeTokenNotUsable = "token.not_usable",
    CodeTokenPIN = "token.pin",
    CodeTokenPINBlocked = "token.pin_blocked",
    CodeTokenPINAgain = "token.pin_required",
    CodeTokenTouch = "token.touch",
    CodeTokenTooMany = "token.too_many_operations",
    CodeTokenReset = "token.reset_failed",
    CodeTokenOccupied = "token.slot_occupied",
    CodeTokenFull = "token.no_empty_slot",
    CodeTokenNoMgmtKey = "token.no_protected_management_key",
    CodeTokenMgmtKey = "token.management_key",
    CodeTokenTwoKeys = "token.two_keys",

    /**
     * Archives.
     */
    CodeArchiveNotOpen = "archive.not_open",
    CodeArchiveOpen = "archive.already_open",
    CodeArchiveDirty = "archive.dirty",
    CodeArchiveBusy = "archive.busy",
    CodeArchiveCompacting = "archive.compacting",
    CodeArchiveNeedsReopen = "archive.needs_reopen",
    CodeArchiveKey = "archive.key",
    CodeArchiveReadOnly = "archive.read_only",
    CodeArchiveNotFound = "archive.not_found",
    CodeArchiveInvalid = "archive.invalid",
    CodeArchiveMissing = "archive.file_missing",
    CodeFileExists = "file.exists",
    CodeFileNotFound = "file.not_found",
    CodeFileName = "file.name",
    CodeSourceChanged = "file.source_changed",
    CodeContentHash = "file.content_hash",
    CodeNoSpace = "archive.no_space",
    CodeDictInUse = "archive.dictionary_in_use",
    CodeOpNotFound = "op.not_found",
    CodeOpCancelled = "op.cancelled",
    CodeOpRunning = "op.in_progress",
    CodeTooSlow = "op.too_slow_for_session",
    CodeParams = "params",
    CodeIO = "io",
};

/**
 * Collision is what CheckNames reports.
 */
export interface Collision {
    "name": string;

    /**
     * the file id of the row it collides with
     */
    "existing": string;
    "pending": boolean;
}

/**
 * FileOutcome is one file's result inside a batch operation.
 */
export interface FileOutcome {
    "path": string;
    "name": string;

    /**
     * added | replaced | renamed | skipped | extracted | failed
     */
    "outcome": string;
    "code"?: Code;
}

/**
 * FileRow is one row of a page.
 */
export interface FileRow {
    "fileId": string;

    /**
     * the full stored name
     */
    "path": string;

    /**
     * the leaf within the folder asked for
     */
    "name": string;
    "size": number;

    /**
     * raw | zstd | zstd+dict
     */
    "storage": string;
    "savedPercent": number;
    "modifiedAt": number;

    /**
     * added | replaced | renamed | deleted
     */
    "pending"?: string;
    "isFolder": boolean;

    /**
     * folders: files under it
     */
    "files": number;
}

/**
 * OpView is a running or finished long operation.
 */
export interface OpView {
    "id": string;
    "kind": string;
    "archiveId"?: string;
    "done": number;
    "total": number;
    "phase": string;
    "startedAt": number;
    "finished": boolean;
    "error"?: Code;
    "results"?: FileOutcome[] | null;
}

/**
 * Page is one screenful of an archive folder.
 */
export interface Page {
    "seq": number;
    "folder": string;
    "rows": FileRow[] | null;
    "total": number;
}

/**
 * Reader is a PC/SC reader that looks like a YubiKey.
 */
export interface Reader {
    "name": string;
}

/**
 * Settings is the machine-local settings file plus the registry's timeouts.
 */
export interface Settings {
    "vaultPath": string;
    "displayName": string;

    /**
     * destroy | hide
     */
    "closeToTray": string;

    /**
     * system | light | dark
     */
    "theme": string;

    /**
     * native
     */
    "look": string;
    "recoveryRecordPct": number;
    "dictionaryBelow": number;

    /**
     * from the registry; 0 = default
     */
    "idleMinutes": number;

    /**
     * from the registry; 0 = default
     */
    "absoluteMinutes": number;
    "timeoutsFromVault": boolean;

    /**
     * only while unlocked
     */
    "timeoutsAdjustable": boolean;
}

/**
 * SlotView describes a way to unlock.
 */
export interface SlotView {
    "recipientId": string;

    /**
     * hardware | password | recovery
     */
    "type": string;
    "label": string;
    "createdAt": number;
    "entangled": boolean;
    "stale": boolean;
}

/**
 * TextPreview is a text file's head for the preview pane.
 */
export interface TextPreview {
    "text": string;
    "truncated": boolean;
}

/**
 * VaultState is the session's state.
 */
export enum VaultState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * no vault configured yet
     */
    StateNone = "none",

    /**
     * keys not in memory
     */
    StateLocked = "locked",

    /**
     * a ceremony is running
     */
    StateUnlocking = "unlocking",

    /**
     * a ceremony is ending; the card is being released
     */
    StateReleasing = "releasing",
    StateUnlocked = "unlocked",

    /**
     * a commit's outcome is unknown; Reopen
     */
    StateBroken = "broken",

    /**
     * the vault file is open in another process
     */
    StateBusy = "busy",
};

/**
 * VaultStatus is the whole state the frontend renders from; every field is
 * safe to show.
 */
export interface VaultStatus {
    "seq": number;
    "state": VaultState;
    "path": string;
    "displayName": string;
    "lastUnlockedAt": number;

    /**
     * idle deadline, 0 when locked
     */
    "locksAt": number;

    /**
     * absolute deadline, 0 when locked
     */
    "absoluteAt": number;

    /**
     * the keystore's own date (R35)
     */
    "modifiedAt": number;
    "rotationPending": boolean;
    "tampered": boolean;
    "warnings": Code[] | null;
    "ceremony"?: CeremonyState | null;
    "ops": OpView[] | null;
    "openArchives": number;
    "dirtyArchives": number;
    "hasPasswordSlot": boolean;
    "hasHardwareSlot": boolean;
}
