// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Archive is an open archive.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function AddFiles(id: string, folder: string, paths: string[] | null, policy: string): $CancellablePromise<string> {
    return $Call.ByID(2769288047, id, folder, paths, policy);
}

export function AddFolder(id: string, folder: string, dir: string, policy: string): $CancellablePromise<string> {
    return $Call.ByID(3008447636, id, folder, dir, policy);
}

export function CancelOp(opID: string): $CancellablePromise<void> {
    return $Call.ByID(2446376312, opID);
}

export function CheckNames(id: string, folder: string, names: string[] | null): $CancellablePromise<app$0.Collision[] | null> {
    return $Call.ByID(1850767145, id, folder, names);
}

export function Delete(id: string, fileIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3839303214, id, fileIDs);
}

export function Discard(id: string): $CancellablePromise<void> {
    return $Call.ByID(2715197693, id);
}

export function Extract(id: string, fileIDs: string[] | null, dir: string, policy: string): $CancellablePromise<string> {
    return $Call.ByID(585645538, id, fileIDs, dir, policy);
}

export function KeepOpen(id: string): $CancellablePromise<void> {
    return $Call.ByID(2470395052, id);
}

export function Op(opID: string): $CancellablePromise<app$0.OpView> {
    return $Call.ByID(448053830, opID);
}

export function Page(id: string, folder: string, sortBy: string, offset: number, limit: number): $CancellablePromise<app$0.Page> {
    return $Call.ByID(2601627082, id, folder, sortBy, offset, limit);
}

/**
 * PreviewText returns up to maxBytes of a text file and whether it was cut.
 */
export function PreviewText(id: string, fileID: string, maxBytes: number): $CancellablePromise<app$0.TextPreview> {
    return $Call.ByID(723007364, id, fileID, maxBytes);
}

export function PreviewURL(id: string, fileID: string): $CancellablePromise<string> {
    return $Call.ByID(913354260, id, fileID);
}

export function Rename(id: string, fileID: string, newLeaf: string): $CancellablePromise<void> {
    return $Call.ByID(3028646727, id, fileID, newLeaf);
}

export function Replace(id: string, fileID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(3231340199, id, fileID, path);
}

export function Save(id: string): $CancellablePromise<string> {
    return $Call.ByID(3912183196, id);
}

export function Stat(id: string): $CancellablePromise<app$0.ArchiveStat> {
    return $Call.ByID(2565212395, id);
}
