// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Archive is an open archive.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function AddFiles(id: string, parentID: string, paths: string[] | null, policy: string): $CancellablePromise<string> {
    return $Call.ByID(2769288047, id, parentID, paths, policy);
}

export function AddFolder(id: string, parentID: string, dir: string, policy: string): $CancellablePromise<string> {
    return $Call.ByID(3008447636, id, parentID, dir, policy);
}

export function CancelOp(opID: string): $CancellablePromise<void> {
    return $Call.ByID(2446376312, opID);
}

/**
 * CheckNames lets the UI ask once before an add: which of the offered names
 * a live child of parentID already holds. A name given with a trailing "/"
 * is offered as a directory, and the collision carries the kind on both
 * sides.
 */
export function CheckNames(id: string, parentID: string, names: string[] | null): $CancellablePromise<app$0.Collision[] | null> {
    return $Call.ByID(1850767145, id, parentID, names);
}

/**
 * CreateFolder commits a directory record and returns its id: a folder is a
 * record, so an empty one is a real thing (FORMAT.md R39).
 */
export function CreateFolder(id: string, parentID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3241529081, id, parentID, name);
}

/**
 * Delete removes each record in one commit; a directory takes its subtree,
 * tombstoned in the same write. The page asks first — a delete cannot be
 * undone (APP.md §3, §6).
 */
export function Delete(id: string, recordIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3839303214, id, recordIDs);
}

export function Extract(id: string, recordIDs: string[] | null, dir: string, policy: string): $CancellablePromise<string> {
    return $Call.ByID(585645538, id, recordIDs, dir, policy);
}

/**
 * Move re-parents each record onto parentID, pre-flighted whole against
 * FORMAT.md R39 and refused whole and in place.
 */
export function Move(id: string, recordIDs: string[] | null, parentID: string): $CancellablePromise<void> {
    return $Call.ByID(191579688, id, recordIDs, parentID);
}

export function Op(opID: string): $CancellablePromise<app$0.OpView> {
    return $Call.ByID(448053830, opID);
}

/**
 * Page lists the children of one directory of the committed snapshot. dirID
 * is a record id — the all-zero id is the archive's root — never a path, and
 * one that no longer names a live directory is file.not_found.
 */
export function Page(id: string, dirID: string, sortBy: string, offset: number, limit: number): $CancellablePromise<app$0.Page> {
    return $Call.ByID(2601627082, id, dirID, sortBy, offset, limit);
}

/**
 * PreviewText returns up to maxBytes of a text file and whether it was cut.
 */
export function PreviewText(id: string, fileID: string, maxBytes: number): $CancellablePromise<app$0.TextPreview> {
    return $Call.ByID(723007364, id, fileID, maxBytes);
}

export function PreviewURL(id: string, fileID: string): $CancellablePromise<string> {
    return $Call.ByID(913354260, id, fileID);
}

export function Rename(id: string, recordID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(3028646727, id, recordID, newName);
}

export function Replace(id: string, fileID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(3231340199, id, fileID, path);
}

export function Stat(id: string): $CancellablePromise<app$0.ArchiveStat> {
    return $Call.ByID(2565212395, id);
}
