// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Archives is the registry's list and the per-archive operations that do
 * not need it open.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(1388822288, id);
}

export function CloseAll(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2300343171);
}

export function Compact(id: string): $CancellablePromise<string> {
    return $Call.ByID(2111968017, id);
}

export function Create(path: string, name: string, noCompression: boolean): $CancellablePromise<string> {
    return $Call.ByID(1162996984, path, name, noCompression);
}

export function Hide(id: string): $CancellablePromise<void> {
    return $Call.ByID(2169725132, id);
}

export function List(showHidden: boolean): $CancellablePromise<app$0.ArchiveSummary[] | null> {
    return $Call.ByID(4176692468, showHidden);
}

export function Locate(id: string, p: string): $CancellablePromise<void> {
    return $Call.ByID(422512670, id, p);
}

export function Open(id: string): $CancellablePromise<app$0.ArchiveStat> {
    return $Call.ByID(923201420, id);
}

export function RotateKey(id: string): $CancellablePromise<string> {
    return $Call.ByID(3689812034, id);
}

export function Unhide(id: string): $CancellablePromise<void> {
    return $Call.ByID(474530495, id);
}

export function Verify(id: string): $CancellablePromise<string> {
    return $Call.ByID(3359801409, id);
}
