// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Archives is the registry's list and the per-archive operations that do
 * not need it open.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

/**
 * CheckFiles refreshes the presence of every record's last_path; the list's
 * Status column follows on archives.changed.
 */
export function CheckFiles(): $CancellablePromise<void> {
    return $Call.ByID(118112595);
}

export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(1388822288, id);
}

export function CloseAll(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2300343171);
}

export function Compact(id: string): $CancellablePromise<string> {
    return $Call.ByID(2111968017, id);
}

export function Create(path: string, name: string, noCompression: boolean): $CancellablePromise<string> {
    return $Call.ByID(1162996984, path, name, noCompression);
}

/**
 * Delete is Forget plus the file when alsoFile is set: the file is removed
 * first and only then is the record forgotten.
 */
export function Delete(id: string, alsoFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(2185012391, id, alsoFile);
}

/**
 * Details is one registry record read whole, for the details pane and its
 * modal: no key material, and refused while the vault is locked.
 */
export function Details(id: string): $CancellablePromise<app$0.ArchiveDetails> {
    return $Call.ByID(2517846314, id);
}

/**
 * Forget drops the record softly: its keys stay until the purge at an unlock
 * more than thirty days later, and Restore brings it back.
 */
export function Forget(id: string): $CancellablePromise<void> {
    return $Call.ByID(2605071885, id);
}

export function Hide(id: string): $CancellablePromise<void> {
    return $Call.ByID(2169725132, id);
}

export function List(showHidden: boolean): $CancellablePromise<app$0.ArchiveSummary[] | null> {
    return $Call.ByID(4176692468, showHidden);
}

export function Locate(id: string, p: string): $CancellablePromise<void> {
    return $Call.ByID(422512670, id, p);
}

export function Open(id: string): $CancellablePromise<app$0.ArchiveStat> {
    return $Call.ByID(923201420, id);
}

/**
 * Rename writes the registry's trusted name (FORMAT.md §7.4); no ceremony.
 */
export function Rename(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2187678638, id, name);
}

export function Restore(id: string): $CancellablePromise<void> {
    return $Call.ByID(2523843286, id);
}

export function RotateKey(id: string): $CancellablePromise<string> {
    return $Call.ByID(3689812034, id);
}

/**
 * SetDescription writes the record's description: at most 1 024 bytes of
 * UTF-8, empty clears it (FORMAT.md §7.1).
 */
export function SetDescription(id: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(48311342, id, text);
}

export function Unhide(id: string): $CancellablePromise<void> {
    return $Call.ByID(474530495, id);
}

export function Verify(id: string): $CancellablePromise<string> {
    return $Call.ByID(3359801409, id);
}
