// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Keys is the ways in, and backups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

/**
 * BeginEnroll adds a way in: "token", "password" or "recovery". An
 * enrolled key inherits the vault's entangled password and is wrapped from
 * the kept K_P, so no password is chosen here (APP.md §13).
 */
export function BeginEnroll(kind: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(309727738, kind, label);
}

/**
 * ChangeEntangledPassword replaces the vault's password; a ceremony, and
 * the old password is never a field.
 */
export function ChangeEntangledPassword(): $CancellablePromise<void> {
    return $Call.ByID(3747209322);
}

/**
 * DropRecoveryKey ends a reveal's handle when its dialog closes.
 */
export function DropRecoveryKey(handle: string): $CancellablePromise<void> {
    return $Call.ByID(3166408438, handle);
}

/**
 * EntangledState is the Keys page's row for the vault's password: whether
 * it is on, and whether the invariant would let it be turned on.
 */
export function EntangledState(): $CancellablePromise<app$0.EntangledState> {
    return $Call.ByID(898464716);
}

export function ExportBackup(path: string): $CancellablePromise<void> {
    return $Call.ByID(3159373965, path);
}

export function RemoveSlot(recipientID: string): $CancellablePromise<void> {
    return $Call.ByID(1280438677, recipientID);
}

/**
 * RevealRecoveryKey shows a recovery slot's key again, after a protector
 * unlock; the digits arrive over the one-time URL, never here.
 */
export function RevealRecoveryKey(recipientID: string): $CancellablePromise<void> {
    return $Call.ByID(207819850, recipientID);
}

export function RotateNow(): $CancellablePromise<void> {
    return $Call.ByID(332274822);
}

/**
 * SaveRecoveryKey writes the key behind a reveal's handle to a path the
 * user chose; the handle is the URL's token, not the digits.
 */
export function SaveRecoveryKey(handle: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3463005426, handle, path);
}

/**
 * SetEntangled turns the vault's password on or off; turning it on asks
 * for the new password, turning it off asks for nothing. Both are
 * ceremonies, and neither ever asks the old password.
 */
export function SetEntangled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2247223905, on);
}

export function Slots(): $CancellablePromise<app$0.SlotView[] | null> {
    return $Call.ByID(632849442);
}

/**
 * VerifyBackup proves a backup opens with its recovery key, on a copy;
 * nothing changes.
 */
export function VerifyBackup(path: string): $CancellablePromise<void> {
    return $Call.ByID(3093488550, path);
}
