// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the machine-local settings plus the registry's timeouts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function Get(): $CancellablePromise<app$0.Settings> {
    return $Call.ByID(2652127606);
}

export function Set(v: app$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(740356410, v);
}
