// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Shell is the window and the native dialogs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(3606391931);
}

export function PickFiles(title: string, multiple: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(3229291943, title, multiple);
}

export function PickFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(2529646972, title);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2079207478);
}

export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(842300112, path);
}

export function SaveFile(title: string, filename: string): $CancellablePromise<string> {
    return $Call.ByID(1923582270, title, filename);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3130426784);
}
