// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Shell is the window and the native dialogs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

/**
 * CloseDecided answers the close question the page asked when the window's
 * close was cancelled (APP.md §2.4, ruled 2026-09-13). action is "tray" or
 * "quit" — never "ask", which is what was being asked — and remember
 * writes it to Settings.CloseAction through the core, exactly as the
 * settings page's own save does, so the next close does not ask. The
 * window then goes to the tray, leaving every page, or the shell's Quit
 * runs.
 */
export function CloseDecided(action: string, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(2169987085, action, remember);
}

export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(3606391931);
}

/**
 * DragOut is the one gesture of APP.md §3: a press-and-move over selected
 * rows starts one native drag of those records out of the window, and this
 * call blocks until DoDragDrop returns — the window stays alive and its
 * page keeps moving meanwhile, the drag having a thread of its own and the
 * main thread being nobody's to hold (ruled 2026-09-11). The staged copy is
 * extracted by the drop's own request under an operation of kind dragout,
 * which the strip follows (preparing, then awaiting) and which ends when
 * the drag reports how it ended (OpView.DragResult). A release over
 * Enfold's own window is a self-drop: nothing is extracted, and the page —
 * receiving the WebView's drop with paths under Folder — performs the Move
 * of the ids it kept in flight. drag.unsupported when no native drag can
 * run, drag.busy while one is running, params for an empty or root
 * selection, and the archive's own codes.
 */
export function DragOut(archiveID: string, recordIDs: string[] | null): $CancellablePromise<app$0.DragOutResult> {
    return $Call.ByID(945813141, archiveID, recordIDs);
}

/**
 * PendingOpen is the page asking, at boot, whether this launch was asked
 * to open a file (APP.md §14). A launch argument cannot be delivered as an
 * event — there is no page to hear it until the window has drawn one — so
 * the shell keeps it and the page comes for it; a second launch, whose
 * page is already up, is told by `shell.open` instead. The answer carries
 * Seq 0 when there is nothing waiting, and the request is cleared by the
 * asking, so it is opened once however it arrived.
 */
export function PendingOpen(): $CancellablePromise<app$0.OpenRequest> {
    return $Call.ByID(1615108156);
}

export function PickFiles(title: string, multiple: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(3229291943, title, multiple);
}

export function PickFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(2529646972, title);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2079207478);
}

/**
 * Reveal shows a path in the file manager. The page prints on its own: the
 * recovery key's window.print() is watched by nothing since 2026-09-09, and
 * pressing Print… counts as done (APP.md §6).
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(842300112, path);
}

export function SaveFile(title: string, filename: string, dir: string): $CancellablePromise<string> {
    return $Call.ByID(1923582270, title, filename, dir);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3130426784);
}
