// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Vault is the session: state, ceremony, lock.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function Activity(): $CancellablePromise<void> {
    return $Call.ByID(2320277474);
}

/**
 * BeginUnlock starts a ceremony: "token", "password" or "recovery". The
 * secrets themselves arrive on the raw message channel, never here.
 */
export function BeginUnlock(method: string): $CancellablePromise<void> {
    return $Call.ByID(1779776360, method);
}

export function CancelUnlock(): $CancellablePromise<void> {
    return $Call.ByID(3770426637);
}

/**
 * CreateVault makes a new vault with a recovery key and a first slot of
 * kind "token" or "password"; the recovery key is shown once through the
 * ceremony's one-time URL. path empty is the one place a vault lives;
 * over a vault kept there, replace must be true (a confirmed replacement).
 */
export function CreateVault(path: string, displayName: string, kind: string, label: string, entangle: boolean, replace: boolean): $CancellablePromise<void> {
    return $Call.ByID(882388909, path, displayName, kind, label, entangle, replace);
}

/**
 * DiscardRecords ends a merge handle: the dialog closed.
 */
export function DiscardRecords(handle: string): $CancellablePromise<void> {
    return $Call.ByID(3468826983, handle);
}

/**
 * FinishSetup gives a vault that has only its recovery key its first way
 * in.
 */
export function FinishSetup(kind: string, label: string, entangle: boolean): $CancellablePromise<void> {
    return $Call.ByID(1994498129, kind, label, entangle);
}

/**
 * ImportFile makes a vault or backup file the vault kept here, once it
 * has proved itself: a vault by unlocking with method ("token",
 * "password", "recovery"), a backup by its recovery key and then the
 * first way in (kind, label, entangle). replace confirms replacing the
 * vault kept here.
 */
export function ImportFile(path: string, displayName: string, method: string, kind: string, label: string, entangle: boolean, replace: boolean): $CancellablePromise<void> {
    return $Call.ByID(18027300, path, displayName, method, kind, label, entangle, replace);
}

/**
 * IncomingRecords is the record list behind a merge handle.
 */
export function IncomingRecords(handle: string): $CancellablePromise<app$0.IncomingRecord[] | null> {
    return $Call.ByID(2398325755, handle);
}

/**
 * InspectFile says what a keystore file is — a vault or a backup — and
 * whether it is this vault and newer, without a credential.
 */
export function InspectFile(path: string): $CancellablePromise<app$0.FileInfo> {
    return $Call.ByID(3319062579, path);
}

/**
 * InspectRecords opens a backup or a vault over a staged copy for a merge:
 * a ceremony for this vault's VMK, ending with a handle in the ceremony
 * state's slotLabel. Nothing of that file is installed.
 */
export function InspectRecords(path: string): $CancellablePromise<void> {
    return $Call.ByID(1148297629, path);
}

/**
 * LastExportAt is when a backup of the vault kept here was last written,
 * in Unix seconds; 0 means never. It words the confirmations of Forget and
 * Delete and pre-selects the rotate dialog's backup checkbox, and gates
 * nothing (APP.md §13).
 */
export function LastExportAt(): $CancellablePromise<number> {
    return $Call.ByID(3774546620);
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(951839700);
}

/**
 * MergeRecords takes the ticked records into this vault's registry: a
 * registry write, no ceremony.
 */
export function MergeRecords(handle: string, ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1344102321, handle, ids);
}

export function OpenVaultFile(path: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(2953146167, path, displayName);
}

export function Readers(): $CancellablePromise<app$0.Reader[] | null> {
    return $Call.ByID(3956196437);
}

export function Reopen(): $CancellablePromise<void> {
    return $Call.ByID(4094929714);
}

export function Status(): $CancellablePromise<app$0.VaultStatus> {
    return $Call.ByID(3940765069);
}
