// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Vault is the session: state, ceremony, lock.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../models.js";

export function Activity(): $CancellablePromise<void> {
    return $Call.ByID(2320277474);
}

/**
 * BeginUnlock starts a ceremony: "token", "password" or "recovery". The
 * secrets themselves arrive on the raw message channel, never here.
 */
export function BeginUnlock(method: string): $CancellablePromise<void> {
    return $Call.ByID(1779776360, method);
}

export function CancelUnlock(): $CancellablePromise<void> {
    return $Call.ByID(3770426637);
}

/**
 * CreateVault makes a new vault with a recovery key and a first slot of
 * kind "token" or "password"; the recovery key is shown once through the
 * ceremony's one-time URL.
 */
export function CreateVault(path: string, displayName: string, kind: string, label: string, entangle: boolean): $CancellablePromise<void> {
    return $Call.ByID(882388909, path, displayName, kind, label, entangle);
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(951839700);
}

export function OpenVaultFile(path: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(2953146167, path, displayName);
}

export function Readers(): $CancellablePromise<app$0.Reader[] | null> {
    return $Call.ByID(3956196437);
}

export function Reopen(): $CancellablePromise<void> {
    return $Call.ByID(4094929714);
}

export function Status(): $CancellablePromise<app$0.VaultStatus> {
    return $Call.ByID(3940765069);
}
